### ISSUE TITLE
Colored spans

### ISSUE THREAD

**Issue by AurelienMassiot** [paperai/pdfanno#119]
It is more a suggestion than an issue : would it be possible to add **colored spans** ? They are currently all yellow -tell me if I'm wrong-. It would be really easier for the annotator to distinct spans.

Thanks again for your great work.

**Comment by hshindo** [comment]
Yes it's possible, but currently only single-colored highlighting is supported for each user.

The reason is I'd like to support multi-user annotations on pdfanno. That is, multiple annotation files (from some annotators) can be rendered simultaneously on a single pdf to check annotation conflicts. This function is currently available as "reference files" on the demo site.
In this case, the colored span is used to distinguish users rather than annotation labels.

However, maybe colored span can be used to distinct annotation labels.
Let me think about it. Any suggestions are welcome.

**Comment by AurelienMassiot** [comment]
Yes, I think colored span could be useful to distinct annotation labels ; for our use case for example, we would like to annotate 4 different labels, and the colour doesn't depend on the annotator(since every annotator labels the same 4 labels) but depends on the label.

**Comment by hshindo** [comment]
Check it out!
https://paperai.github.io/pdfanno/latest/

**Comment by hshindo** [comment]
fixed.

**Comment by AurelienMassiot** [comment]
Thanks !
